export const ALL_TOPICS: string[] = [
  "Notícias mundiais",
  "Economia",
  "Investimentos",
  "Finanças pessoais",
  "Negócios",
  "Empreendedorismo",
  "Psicologia",
  "Comportamento humano",
  "Manipulação",
  "Negociação",
  "Comunicação",
  "Liderança",
  "História",
  "Filosofia",
  "Política",
  "Geopolítica",
  "Sociologia",
  "Ciência",
  "Física",
  "Química",
  "Biologia",
  "Espaço",
  "Inteligência Artificial",
  "Tecnologia",
  "Cibersegurança",
  "Carros",
  "Motas",
  "Aviação",
  "Barcos",
  "Arquitetura",
  "Design",
  "Engenharia",
  "Medicina",
  "Nutrição",
  "Fitness",
  "Longevidade",
  "Sobrevivência",
  "Produtividade",
  "Hábitos",
  "Curiosidades",
  "Crimes famosos",
  "Teorias científicas",
  "Invenções",
  "Luxo",
  "Marcas",
  "Marketing",
  "Vendas",
  "Linguagem corporal",
  "Estatística",
  "Matemática aplicada",
  "Animais",
  "Oceanos",
  "Países",
  "Culturas",
  "Religião",
  "Arte",
  "Música",
  "Cinema",
  "Poesia",
  "Frases filosóficas",
  "Frases históricas",
  "Leis estranhas",
  "Paradoxos",
  "Mistérios do mundo",
  "Descobertas recentes",
  "Tendências futuras",
  "Erros cognitivos",
  "Truques mentais",
  "Dinheiro e poder",
];

export function parseTopicsParam(value: string | null | undefined): string[] {
  if (!value) return [];
  return value
    .split(",")
    .map((t) => t.trim())
    .filter((t) => t.length > 0);
}
